export const LOCAL_URL = 'http://52.34.207.5:3038';
// export const SERVER_URL = 'http://52.34.207.5:4117';
const API_END_PREFIX = 'api/';

export const LOGIN = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
}
export const SIGNUP = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILED: 'SIGNUP_FAILED',
}
export const FORGOTPASSWORD = {
    FORGOTPASSWORD_REQUEST: 'FORGOTPASSWORD_REQUEST',
    FORGOTPASSWORD_SUCCESS: ' FORGOTPASSWORD_SUCCESS',
    FORGOTPASSWORD_FAILED: ' FORGOTPASSWORD_FAILED',
}
export const SUPPLIER = {
    SUPPLIER_REQUEST: 'SUPPLIER_REQUEST',
    SUPPLIER_SUCCESS: ' SUPPLIER_SUCCESS',
    SUPPLIER_FAILED: ' SUPPLIER_FAILED',
}